network/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("like/<int:id>", views.like, name="like"),
    path("editpost/<int:id>", views.editpost, name="editpost"),	
	path("delete_post/<str:post>", views.delete_post, name="delete_post"),
    path("follow/<int:id>", views.follow, name="follow"),
    path("following", views.following, name="following"),
    path("post_message", views.post_message, name="post_message"),    
    path("profile/<str:username>", views.profile, name="profile"),
	path("add_image", views.add_image, name="add_image"),
    path("account/<str:username>", views.account_view, name="account_view")	
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime

class User(AbstractUser):
    pass    

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=300, default=None)
    date = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return f"{self.id}: {self.user}'s post: {self.text}"
		

class Picture(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='imageprofile')
    image = models.ImageField(upload_to='images', null=True)
	
    def __str__(self):
        return f"{self.id}: {self.user}"	
		
		
class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    class Meta:
        unique_together = (('post', 'user'),)
    def __str__(self):
        return f"{self.post} : {self.user}"
		
		
class Follower(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower', default=None)
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following', default=None)

    class Meta:
        unique_together = (('follower', 'following'),)
    def __str__(self):
            return f"{self.follower} : {self.following}"

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
import time
from django.urls import reverse
from django.core.paginator import Paginator
from django.views.generic import ListView
from network.models import *
from django.db.models import *
from django import forms

max_posts = 10


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        if request.user.is_anonymous:
            return render(request, "network/login.html")
        else: 
            return redirect('index')



def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))
	

def account_view(request, username):
    user = request.user      
    user_picture = User.objects.get(username=user)
    pictures = Picture.objects.filter(user=user_picture)
    pictures_count = pictures.count()
    if pictures_count == 0:
        picture = Picture.objects.get(id=12)
    else:
        sum = 0
        for picture in pictures:
            sum+=1
            if sum == 1:
                continue
    if request.method == 'GET':
        profile = User.objects.get(username=username)
        if request.user.is_anonymous:
            return redirect("login")
        if profile.username == user.username:
            return render(request, "network/account.html", {
			"form": PictureForm(),
            "picture": picture,
			"profile": profile,				
			})
        else:
            return redirect("index")
		
    else: 
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        email = request.POST["email"]
        
        profile = User.objects.get(username=username)
        profile.first_name = first_name
        profile.last_name = last_name        
        email_exist = User.objects.filter(email=email)
        if not email_exist or profile.email == email:
            profile.email = email
        else:
            return render(request, "network/account.html", {
			    "form": PictureForm(),
                "picture": picture,
			    "profile": profile, 				
				"message": "Email already taken"})        
        profile.save()        
        return render(request, "network/account.html",{
		    "message": "Account details has been updated successfully"})
		
		
def add_image(request):        
    user = request.user      
    user_picture = User.objects.get(username=user)
    pictures = Picture.objects.filter(user=user_picture)
    pictures_count = pictures.count()
    if pictures_count == 0:
        picture = Picture.objects.get(id=12)
    else:
        sum = 0
        for picture in pictures:
            sum+=1
            if sum == 1:
                continue
    if user.id is None:
        return redirect('login')		

    if request.method == 'GET':	    
        return render(request, "network/add_image.html", {
		    "picture": picture,
            "form": PictureForm()            
        })   
	
    else:    
        form = PictureForm(request.POST, request.FILES)
		
        if form.is_valid():               
            image = form.cleaned_data['image']
            imageCreated = Picture.objects.create( 
                user=request.user,			
                image=image
            )
            return render(request, "network/add_image.html",{
			    "form": form,
                "picture": picture,
                "imageCreated":imageCreated,
		        "message": "Image uploaded successfully"})            
            

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if not username:
            return render(request, "network/register.html", {
                "message": "You must enter a username."})
        
        if not email:
            return render(request, "network/register.html", {
                "message": "You must enter an email."})

        if not password:
            return render(request, "network/register.html", {
                "message": "You must enter a password."})
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            email_exist = User.objects.filter(email=email)
            if not email_exist:
                user = User.objects.create_user(username, email, password)
                user.save()
            else:
                return render(request, "network/register.html", {
                "message": "Email has already been taken."
            })
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "*Username already taken."
            })
        login(request, user)
        return redirect("account_view", username)
    else:
        if request.user.is_anonymous:
            return render(request, "network/register.html")
        else:
            return redirect('index')


def index(request):
    user = request.user
    if not request.user.is_authenticated:
        picture = Picture.objects.get(id=12)
    else:
        user_picture = User.objects.get(username=user)
        pictures = Picture.objects.filter(user=user_picture)
        pictures_count = pictures.count()
        if pictures_count == 0:
            picture = Picture.objects.get(id=12)
        else:
            sum = 0
            for picture in pictures:
                sum += 1
                if sum == 1:
                    continue
    if request.user.is_authenticated:
        user = request.session["_auth_user_id"]
        likes = Like.objects.filter(post=OuterRef("id"), user_id=user)
        posts = Post.objects.filter().order_by("-date").annotate(current_like=Count(likes.values("id")))
    else:
        posts = Post.objects.order_by("-date").all()
    paginator = Paginator(posts, max_posts)
    page_no = request.GET.get("page")
    post_items = paginator.get_page(page_no)
    return render(request, "network/index.html", {
        "posts": post_items,
        "picture": picture,
        "form": NewPost(),
        "edit_post": EditPost()
    })


def following(request):
    user = request.user      
    user_picture = User.objects.get(username=user)
    pictures = Picture.objects.filter(user=user_picture)
    pictures_count = pictures.count()
    if pictures_count == 0:
        picture = Picture.objects.get(id=12)
    else:
        sum = 0
        for picture in pictures:
            sum+=1
            if sum == 1:
                continue
    if request.user.is_authenticated:
        user = request.session['_auth_user_id']
        followers = Follower.objects.filter(follower=user)
        likes = Like.objects.filter(post=OuterRef('id'), user_id=user)
        posts = Post.objects.filter(user_id__in=followers.values('following_id')).order_by(
            "-date").annotate(current_like=Count(likes.values('id')))
    else:
        return HttpResponseRedirect(reverse("login"))

    paginator = Paginator(posts, max_posts)
    page_no = request.GET.get('page')
    post_items = paginator.get_page(page_no)
    return render(request, "network/following.html", {
        "posts": post_items,
        "picture": picture,
        "form": NewPost()
    })


def follow(request, id):
    try:
        sequel = 'follow'
        user = User.objects.get(id=request.session['_auth_user_id'])
        fan = User.objects.get(id=id)
        follower = Follower.objects.get_or_create(follower=user, following=fan)
        if not follower[1]:
            Follower.objects.filter(follower=user, following=fan).delete()
            sequel = 'unfollow'
        followers = Follower.objects.filter(following=fan).count()
    except KeyError:
        return HttpResponseBadRequest("Bad Request: There are no followers")
    return JsonResponse({
	    "sequel": sequel, 
	    "total_followers": followers
	})
    
    
def post_message(request):

    if request.method == "POST":
        form = NewPost(request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.session['_auth_user_id'])            
            text = form.cleaned_data["post_text"]
            post = Post(user=user, text=text)
            post.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        return HttpResponseRedirect(reverse("index"))


def editpost(request, id):
    if request.is_ajax and request.method == "POST":
        form = EditPost(request.POST)
        if form.is_valid():
            text = form.cleaned_data["edit_text"]
            Post.objects.filter(
                id=id, user_id=request.session['_auth_user_id']).update(text=text)
            return JsonResponse({"result": 'ok', 'text': text})
        else:
            return JsonResponse({"error": form.errors}, status=400)

    return JsonResponse({
	    "error": HttpResponseBadRequest("Bad Request: no like chosen")}, 
		status=400
	)
	

def delete_post(request, post):
    if request.method == 'POST':
        post = Post.objects.get(id=post)
        post.delete()
        return HttpResponse('success')
		
		
def like(request, id):

network/templates/network/account.html
{% extends "network/layout.html" %}

{% block body %}

{% include "network/profile_picture.html" %}
<hr />
<div class="container Account">
    {% if message %}
        <div class="data-info">{{ message }}</div>
    {% endif %}

    <form action="{% url 'account_view' username=request.user %}" method="POST" >
        {% csrf_token %}
        <div class="form-group">
            <label class="label-account"><strong>First Name</strong></label>
            <input class="form-control" type="text" name="first_name" placeholder="First Name" value="{{user.first_name|title}}">
        </div>
        <div class="form-group">
            <label class="label-account"><strong>Last Name</strong></label>
            <input class="form-control" type="text" name="last_name" placeholder="Last Name" value="{{user.last_name|title}}">
        </div>
        <div class="form-group">
            <label class="label-account"><strong>Email</strong></label>
            <input class="form-control" type="email" name="email" placeholder="Email" value="{{user.email}}">
        </div>		
        <input class="btn btn-outline-dark login-buttom save" type="submit" value="Save">		
    </form>
</div>
<hr />
<div class="card">
    <div class="card-body">
	    <center>
		    <h4> What would you like to do?</h4>
	        <button onclick="window.location.href='{% url 'profile' username=request.user %}'"> Go to Profile Page</button>
            <button onclick="window.location.href='{% url 'add_image' %}'">Upload Profile Image</button>
        </center>        
	</div>
</div>

<hr />
{% endblock %}

network/templates/network/add_image.html
{% extends "network/layout.html" %}

{% block body %}

{% include "network/profile_picture.html" %}
<hr />
<div class="card">
    <div class="card-body">	
    {% if imageCreated %}
      <h3 id="update_picture">Succesfully updated : {{imageCreated.user | title}}'s Profile Image</h3>
      <img src="{{ imageCreated.image.url}}" alt="connect" style="max-height:300px">
    {% endif %}
    {% if message %}
        <div class="data-info">{{ message }}</div>
    {% endif %}
    <div class="add-image">
        <h2 class="title">Select a New Profile Image</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="btn-right">
                <input class="btn btn-outline-dark" type="submit" value="Upload">
            </div>
        </form>
    </div>
	</div>	
</div>
<hr />
<div class="card">
    <div class="card-body" style="background-color:#00001a;">
	    <center>		    
	        <button onclick="window.location.href='{% url 'profile' username=request.user %}'"> Go to Profile Page</button>            
        </center>        
	</div>
</div>
<hr />
{% endblock %}

network/templates/network/following.html
{% extends "network/layout.html" %}

{% block body %}
{% include "network/profile_picture.html" %}
<center><strong class="all_posts">Following</strong></center>
<div id="posts">
    {% for post in posts %}
	
	<div class="card border-secondary mb-3 post-object{{post.id}}">
        <h5 class="card-header"><a href="{% url 'profile' post.user.username %}">{{post.user.username|capfirst}}</a></h5>
        <div class="card-body text-secondary">
            <h6 class="card-subtitle mb-2 text-muted">{{post.date}}</h6>
            <p class="card-text" id="tweet{{post.id}}"> {{ post.text }}</p>
			<form action="#" method="POST" id="form_edit{{post.id}}" data-id="{{post.id}}" style="display: none">
                {% csrf_token %}
                <div class="form-group">
                    {{ edit_post.edit_text }}
                </div>
                <div id="post_alert{{post.id}}">
                </div>
                <div id="post_button">
                <button type="button" data-id="{{post.id}}" id="close_btn{{post.id}}" class="btn btn-secondary"
                    data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="btnSave">Save changes</button>
                </div>
            </form>	            
			<p class="card-text">
                <div data-id="{{post.id}}"
                    class="card-link {% if post.current_like > 0 %} fas {%else%} far {% endif %} fa-heart">&nbsp<small
                        class="text-muted">{{post.like_set.count}}</small>
                </div>
            </p>
            		
        </div>
    </div>    
    {% empty %}
    <h2 class="update_info">No posts</h2>
    {% endfor %}
</div>
{% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}
    {% include "network/profile_picture.html" %}
<center><strong class="all_posts">All Posts</strong></center>
    {% include "network/post_form.html" %}
<div id="posts">
    {% for post in posts %}	
	<div class="card border-secondary mb-3 post-object{{post.id}}">
        <h5 class="card-header"><a href="{% url 'profile' post.user.username %}">{{post.user.username|capfirst}}</a>
		    {% if post.user_id == user.id %}
		        <object align="right"><a href="#" class="card-link" id="edit_link_{{post.id}}" data-id="{{post.id}}" data-toggle="modal">Edit</a></object>
		    {% endif %}		
		</h5>
        <div class="card-body text-secondary">
            <h6 class="card-subtitle mb-2 text-muted">{{post.date}}</h6>
            <p class="card-text" id="tweet{{post.id}}"> {{ post.text }}</p>
			<form action="#" method="POST" id="form_edit{{post.id}}" data-id="{{post.id}}" style="display: none">
                {% csrf_token %}
                <div class="form-group">
                    {{ edit_post.edit_text }}
                </div>
                <div id="post_alert{{post.id}}">
                </div>
                <div id="post_button">
                <button type="button" data-id="{{post.id}}" id="close_btn{{post.id}}" class="btn btn-secondary"
                    data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="btnSave">Save changes</button>
                </div>
            </form>			
            {%if post.user_id == user.id %}				
				<form id="deletePost" data-post='{{post.id}}' action="{% url 'delete_post' post=post.id %}">
                    {% csrf_token %}                            
                    <button class="btn btn-outline-dark" type="submit" onClick="window.location.reload();" >Delete</button>
                </form>
		    {% else %}
			    <p class="card-text">
                    <div data-id="{{post.id}}"
                        class="card-link {% if post.current_like > 0 %} fas {%else%} far {% endif %} fa-heart">&nbsp<small
                            class="text-muted">{{post.like_set.count}}</small>
                    </div>
                </p>
            {% endif %}			
        </div>
    </div>   
    {% empty %}
    <h2 class="update_info">No posts</h2>
    {% endfor %}
</div>


{% endblock %}

network/templates/network/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Social Media Site{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">		
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>        
    <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet">
    <link href="{% static 'network/styles.css' %}" rel="stylesheet">
	
</head>

<body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        
            <a class="navbar-brand" href="{% url 'index' %}"><b style="font-size1:30px;">Network</b></a>            
            <div>
	            {% with request.resolver_match.url_name as url_name %}
                    <ul class="navbar-nav mr-auto">
	                    {% if user.is_authenticated %}
                            <li class="nav-item {% if url_name == 'profile' %}active{% endif %}" >
                                <a class="nav-link active" aria-current="page" href="{% url 'profile' user.username %}"><strong>{{ user.username|capfirst }}</strong></a>
                            </li>
		                {% endif %}
		                <li class="nav-item {% if url_name == 'index' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'index' %}">All Posts</a>
                        </li>
		                {% if user.is_authenticated %}   
                            <li class="nav-item {% if url_name == 'following' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'following' %}">Following</a>
                            </li>
			                <li class="nav-item {% if url_name == 'logout' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                            </li>			
		                {% else %}
                            <li class="nav-item {% if url_name == 'login' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'login' %}">Log In</a>
                            </li>
                            <li class="nav-item {% if url_name == 'register' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'register' %}">Register</a>
                            </li>
                        {% endif %}	             		
                    </ul>
	            {% endwith %}
            </div>
           
        </nav>	 

    <div class="body">
        {% block body %}
        {% endblock %}
        <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">
                    Previous
                </a>
            </li>
            {% endif %}
            {%if posts.paginator.num_pages > 1 %}
            {% for num in posts.paginator.page_range %}
            {% if posts.number == num %}
            <li class="page-item active">
                <a class="page-link">{{ num }}</a>
            </li>
            {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% endif %}
            {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">
                    Next
                </a>
            </li>
            {% endif %}
        </ul>
    </div>

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="{% static 'network/main.js' %}"></script>

</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}
<center>
<div class="wrapper">    
    <strong id="profile_name">Login</strong>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}
<div>
<center>

network/templates/network/profile.html
{% extends "network/layout.html" %}

{% block body %}
<div class="card">
    <div class="card-body">
	    <div>		
		    {%if user.is_authenticated and user.id != profile_account.id %}
			    <img class="img-fluid" src="{{picture.image.url}}" alt="Profile Picture" style="max-height:100px">
	            <strong class="card-title" id="profile_name">{{profile_account.first_name|capfirst}} {{profile_account.last_name|capfirst}}</strong>                				
	        {% else %}
			    <a href="{% url 'account_view' username=request.user %}" class="card-link btn btn-outline-network">
                    <img class="img-fluid" src="{{picture.image.url}}" alt="Profile Picture" style="max-height:100px">	                
	                <strong class="card-title" id="profile_name">{{profile_account.first_name|capfirst}} {{profile_account.last_name|capfirst}}</strong>
				</a>
				<button onclick="window.location.href='{% url 'account_view' username=request.user %}'"> Update your profile details</button>
	        {% endif %}        		
		    <object align="right" class="profile_info">
			    <span class="btn-total-follow">Username: <strong>{{profile_account.username|capfirst}};</strong></span>
			    <span class="btn-total-follow">Total post(s): <strong>{{post_count}}</strong> </span>
			</object>
		</div>
        <hr />
		<button type="button" class="btn-total-follow follows" data-toggle="modal" data-target="#following">{{following_count}} Following </button>
        <button type="button" class="btn-total-follow follows" data-toggle="modal" data-target="#follower" >Followers</button>        
        <strong><span id="followers">{{followers}}</span> Follower(s)</strong>
        </p>
		<hr />
		<div class="modal fade" id="following" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title details-name" id="exampleModalLongTitle">Total Following: {{following_count}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% for follow in following %}
                            <p class="card-header"><a href="{% url 'profile' username=follow.following %}">{{follow.following|title}}</a></p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
		
		<div class="modal fade" id="follower" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title details-name" id="exampleModalLongTitle">Total Followers: {{followers}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% for follow in follower %}
                            <p class="card-header"><a href="{% url 'profile' username=follow.follower %}">{{follow.follower|title}}</a></p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
		
		
        <p class="card-text"><small class="text-muted"></small></p>
        {% if user.is_authenticated and user.id != profile_account.id %}
            <p class="card-text">
            {% if person_count > 0 %}
                <button id="followering_btn" data-id="{{profile_account.id}}" type="button" class="btn btn-primary">Following</button>
            {% else %}
                <button id="followering_btn" data-id="{{profile_account.id}}" type="button" class="btn btn-outline-primary">Follow</button>
            {%endif%}
            </p>
        {%endif%}
    </div>
</div>        

<div id="content">
    {% if user.is_authenticated and user.id != profile_account.id %}
	    <h3>{{profile_account.username|capfirst}}'s Posts</h3>	    
	{% else %}
	    {% include "network/post_form.html" %}
	    <h3>Here are your Personal Posts</h3>	
	{%endif%}
    {% for post in posts %}
	
	<div class="card border-secondary mb-3 post-object{{post.id}}">
        <h5 class="card-header"><a href="{% url 'profile' post.user.username %}">{{post.user.username|capfirst}}</a>
		    {% if post.user_id == user.id %}
		        <object align="right"><a href="#" class="card-link" id="edit_link_{{post.id}}" data-id="{{post.id}}" data-toggle="modal">Edit</a></object>
		    {% endif %}		
		</h5>
        <div class="card-body text-secondary">
            <h6 class="card-subtitle mb-2 text-muted">{{post.date}}</h6>
            <p class="card-text" id="tweet{{post.id}}"> {{ post.text }}</p>
			<form action="#" method="POST" id="form_edit{{post.id}}" data-id="{{post.id}}" style="display: none">
                {% csrf_token %}
                <div class="form-group">
                    {{ edit_post.edit_text }}
                </div>
                <div id="post_alert{{post.id}}">
                </div>
                <div id="post_button">
                <button type="button" data-id="{{post.id}}" id="close_btn{{post.id}}" class="btn btn-secondary"
                    data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="btnSave">Save changes</button>
                </div>
            </form>			
            {%if post.user_id == user.id %}				
				<form id="deletePost" data-post='{{post.id}}' action="{% url 'delete_post' post=post.id %}">
                    {% csrf_token %}                            
                    <button class="btn btn-outline-dark" type="submit" onClick="window.location.reload();" >Delete</button>
                </form>
		    {% else %}
			    <p class="card-text">
                    <div data-id="{{post.id}}"
                        class="card-link {% if post.current_like > 0 %} fas {%else%} far {% endif %} fa-heart">&nbsp<small
                            class="text-muted">{{post.like_set.count}}</small>
                    </div>
                </p>
            {% endif %}			
        </div>
    </div>     
    {% empty %}
    <h2 class="update_info">No posts</h2>
    {% endfor %}
</div>
{% endblock %}